name: devmarket_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0 <3.25.0"

dependencies:
  flutter:
    sdk: flutter

  overlay_support: ^2.1.0  

  # Autenticación y Cuentas
  google_sign_in: ^7.2.0
  
  # Diseño y Estilos
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0

  # Conectividad y HTTP (Manejado con Dio principalmente)
  dio: ^5.9.2
  http: ^1.6.0
  url_launcher: ^6.3.2
  
  # Almacenamiento seguro
  flutter_secure_storage: ^10.3.1
  
  # Comunicación en Tiempo Real (Sockets actualizados para mayor estabilidad)
  socket_io_client: ^3.1.2

  # Pasarela de Pagos
  flutter_stripe: ^13.0.0
  flutter_web_auth_2: ^5.0.3
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/